"""Sync legacy schema with current models

Revision ID: 2ea7c4d5b43b
Revises: 7b0000000001
Create Date: 2026-08-18 12:34:02.925165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ea7c4d5b43b'
down_revision: Union[str, Sequence[str], None] = '7b0000000001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    is_postgres = bind.dialect.name == 'postgresql'
    naming_convention = {
        "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
        "uq": "uq_%(table_name)s_%(column_0_name)s",
    }
    if is_postgres:
        op.execute("ALTER TABLE alumni DROP CONSTRAINT IF EXISTS uq_alumni_email;")
        op.execute("ALTER TABLE alumni DROP CONSTRAINT IF EXISTS alumni_email_key;")
        op.execute("ALTER TABLE users DROP CONSTRAINT IF EXISTS uq_users_email;")
        op.execute("ALTER TABLE users DROP CONSTRAINT IF EXISTS users_email_key;")

    with op.batch_alter_table(
        'alumni', naming_convention=naming_convention
    ) as batch_op:
        batch_op.alter_column(
            'name', existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            'email', existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            'created_at',
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(),
            existing_nullable=True,
            existing_server_default=sa.text('(NULL)'),
        )
        batch_op.create_index('ix_alumni_email', ['email'], unique=True)
        if not is_postgres:
            batch_op.drop_constraint('uq_alumni_email', type_='unique')
        batch_op.create_foreign_key(
            'fk_alumni_user_id_users',
            'users',
            ['user_id'],
            ['id'],
            ondelete='SET NULL',
        )

    with op.batch_alter_table(
        'users', naming_convention=naming_convention
    ) as batch_op:
        batch_op.alter_column(
            'created_at',
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(),
            existing_nullable=True,
            existing_server_default=sa.text('(NULL)'),
        )
        batch_op.create_index('ix_users_email', ['email'], unique=True)
        if not is_postgres:
            batch_op.drop_constraint('uq_users_email', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    naming_convention = {
        "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
        "uq": "uq_%(table_name)s_%(column_0_name)s",
    }
    with op.batch_alter_table(
        'users', naming_convention=naming_convention
    ) as batch_op:
        batch_op.create_unique_constraint('uq_users_email', ['email'])
        batch_op.drop_index('ix_users_email')
        batch_op.alter_column(
            'created_at',
            existing_type=sa.DateTime(),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
            existing_server_default=sa.text('(NULL)'),
        )

    with op.batch_alter_table(
        'alumni', naming_convention=naming_convention
    ) as batch_op:
        batch_op.drop_constraint(
            'fk_alumni_user_id_users', type_='foreignkey'
        )
        batch_op.create_unique_constraint('uq_alumni_email', ['email'])
        batch_op.drop_index('ix_alumni_email')
        batch_op.alter_column(
            'created_at',
            existing_type=sa.DateTime(),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
            existing_server_default=sa.text('(NULL)'),
        )
        batch_op.alter_column(
            'email', existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            'name', existing_type=sa.VARCHAR(), nullable=True
        )
    # ### end Alembic commands ###
